# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/LetsSpeak',
                'doc_host': 'https://yuval6957.github.io',
                'git_url': 'https://github.com/yuval6957/LetsSpeak',
                'lib_path': 'LetsSpeak'},
  'syms': {'LetsSpeak.core': {'LetsSpeak.core.foo': ('core.html#foo', 'LetsSpeak/core.py')}}}
